---
title: "Group Assignment"
output: pdf_document
date: '2022-04-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Group: 17  
Group members:  
• Andre Fontes
• Ewelina Holm Bistrup
• Narong Nuanmuang
• Elena Krismer


## Discussions  
# What did you find most challenging about creating a shiny app?  
Understanding of app structures and functions including organizing the outlooks.

# What do you feel are the benefits and challenges with using golem for app development?  
The golem shiny app is systemic and applicable function for other data.

# Maintaining reproducibility when using shiny apps is a challenge. As an example, some pharma-companies display databases to medical doctors for pointy-clicky data exploration. What are your thoughts on maintaining reproducibility in that scenario? What if the database is updated or the app is updated with new or changed functionality?  
The pharma-company app concept should be easier and better than last version. The changed functionality might give medical doctors feel unfamiliar with new outlook and need time to use the app.

# What other challenges and limitations do you see shiny apps may have? Please elaborate.  
There are many options for creating primary layout and module, the new developer need time to learn and find the proper with their own user.


# Links to app and GitHub  
[Shiny app](https://ei3vp1-narong-nuanmuang.shinyapps.io/group17shiny/)  
[GitHub repo](https://github.com/rforbiodatascience22/group_17_shiny) 
